name: eataly
description: A new Flutter project.

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/rectangle.png
    - assets/eataly.png
    - assets/backgroundimage.png
    - assets/facebook.png
    - assets/google.png
    - assets/search.png
    - assets/bagh.png
    - assets/baghh.png
    - assets/junoon.png
    - assets/arrowleft.png
    - assets/cross.png
    - assets/clock.png
    - assets/fastfood.png
    - assets/objects.png
    - assets/addfriends.png
    - assets/addfriendss.png
    - assets/notification.png
    - assets/wallet.png
    - assets/happyemoji.png
    - assets/cup.png
    - assets/tagright.png
    - assets/vuesax.png
    - assets/copylink.png
    - assets/sharelink.png
    - assets/qrcode.png
    - assets/eddie.png
    - assets/dot.png
    - assets/rec.png
    - assets/rec1.png
    - assets/dot1.png
    - assets/freddie.png
    - assets/audrey.png
    - assets/romanov.png
    - assets/mark.png
    - assets/albert.png
    - assets/michaela.png
    - assets/lim.png
    - assets/alex.png
    - assets/arthur.png
    - assets/lucas.png
    - assets/luke.png




    
    

    
    



  fonts:
    - family: Forum
      fonts:
        - asset: assets/fonts/Forum.ttf










    

